# Generated by Django 6.1 on 2026-08-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assessmentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeTrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('gaze_x', models.FloatField()),
                ('gaze_y', models.FloatField()),
                ('pupil_diameter', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_tracking_data', to='accounts.assessmentsession')),
            ],
        ),
    ]
